### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by xtrasmal** [matthiasnoback/high-quality-bundles-project#1]
Hi Matthias,

Can you try following the readme and see where it takes you? 

-edit- 
see comment below

**Comment by hacfi** [comment]
@xtrasmal Do you mean the numbering stops at 3 or what do you mean exactly??

**Comment by xtrasmal** [comment]
Sorry, I'll be more explicit. 
All the instructions after step 3 do not go like they say. 

Problem1:
Doctrine:schema:create tells me: No Metadata Classes to process.

Problem2:
So then I've manually downloaded the zip file and did a composer update, but then it tells me I have required packages that do not have the required versions.

**Comment by hacfi** [comment]
@xtrasmal You seem to have used `v0.1.0` which indeed doesn’t seem to work (you must have left out the `dev-master` of step 1).
Try `composer create-project matthiasnoback/high-quality-bundles-project bundle-project dev-master` again.

@matthiasnoback Maybe release a new version so people don’t get an error (and the old symfony/symfony v2.4.5)!?

**Comment by xtrasmal** [comment]
...and maybe the amazing xtrasmal/TacticianBundle   :dancers:

**Comment by xtrasmal** [comment]
@hacfi Thanks for the info. I'm doing the dev-master right now. It is really stupid, but if it works, then it is because the  `composer create-project ...etc` field in the readme seems to have a hidden scrollbar. So the `dev-master` part is not visible :dancer:

**Comment by hacfi** [comment]
True! And the last version should work.

Already starred TacticianBundle and will give it a try within the next few weeks :)

**Comment by xtrasmal** [comment]
@hacfi  :+1:  the `dev-master` solved it. Got it all setup like the readme said. Have fun!

**Comment by hacfi** [comment]
@xtrasmal Great! Make sure to checkout the branches of this repo. Branch `milan` is the latest version afaik. I think master is just the starting point of his workshops and those branches show the final version after his refactoring (moving everything non-Symfony-specific out of the bundle).

@matthiasnoback Could be a good idea to explain the repo more in the README?

**Comment by xtrasmal** [comment]
I've got the master repo set up twice. One for the training next week and one which I will refactor myself, so I can compare my work against his teachings, if you know what I mean.

**Comment by hacfi** [comment]
Good..just wasn’t sure whether you were aware that master is the starting point and not the final result. His trainings are great..enjoy!!

**Comment by matthiasnoback** [comment]
Glad it works @xtrasmal Thanks @hacfi for helping out. I've added a note about this problem to the README.
